name: reminder
description: My new Reminder app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  auto_route: ^4.1.0
  bloc: ^8.0.3
  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  intl: ^0.17.0
  smartstruct: ^1.2.6

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  smartstruct_generator: ^1.2.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/lang/
